name: 'Run Cypress tests'
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install dependencies
        uses: cypress-io/github-action@v6.5.0
        with:
          runTests: false
      - name: Run Cypress
        uses: cypress-io/github-action@v6.5.0
        env:
          CYPRESS_BASE_URL: https://nextjs-auth-beryl.vercel.app/
          CYPRESS_SECRET: ${{ secrets.CYPRESS_SECRET }}
          CYPRESS_RETRIES: 2
      - name: Upload videos
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          retention-days: 1
          name: cypress-videos
          path: "${{github.workspace}}/cypress/videos"
      - name: Upload screenshots
        uses: actions/upload-artifact@v3.1.2
        if: failure()
        with:
          retention-days: 1
          name: cypress-screenshots
          path: "${{github.workspace}}/cypress/screenshots"
            
            
